/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.login;

import com.MenuPrincipal.FrmMenuPrincipal;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;

/**
 *
 * @author PC
 */
public class FrmLogin extends javax.swing.JFrame {

    /**
     * Creates new form FrLogin
     */
    FrmMessageError message;
    FrmMenuPrincipal frm;
    public FrmLogin() {
        initComponents();
        frm = new FrmMenuPrincipal();
        message = new FrmMessageError();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnLogo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        passContra = new javax.swing.JPasswordField();
        pnIngresar = new javax.swing.JPanel();
        lbIngresar = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        pnDatos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnExit = new javax.swing.JPanel();
        lbExit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnLogo.setBackground(new java.awt.Color(255, 255, 255));
        pnLogo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel2.setText("Cipriano");
        pnLogo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/favLogo.png"))); // NOI18N
        pnLogo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel4.setText("Iniciar Sesion");
        pnLogo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        jLabel5.setText("Usuario");
        pnLogo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        jLabel6.setText("Contraseña");
        pnLogo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        txtUsuario.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(153, 153, 153));
        txtUsuario.setText("Ingrese su nombre de usuario");
        txtUsuario.setBorder(null);
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsuarioMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUsuarioMousePressed(evt);
            }
        });
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyTyped(evt);
            }
        });
        pnLogo.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 180, -1));

        passContra.setForeground(new java.awt.Color(153, 153, 153));
        passContra.setText("*************");
        passContra.setBorder(null);
        passContra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passContraMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passContraMousePressed(evt);
            }
        });
        passContra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passContraKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passContraKeyTyped(evt);
            }
        });
        pnLogo.add(passContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 180, -1));

        pnIngresar.setBackground(new java.awt.Color(22, 22, 22));
        pnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        pnIngresar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbIngresar.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        lbIngresar.setForeground(new java.awt.Color(255, 255, 255));
        lbIngresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIngresar.setText("Ingresar");
        lbIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbIngresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbIngresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbIngresarMouseExited(evt);
            }
        });
        lbIngresar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lbIngresarKeyPressed(evt);
            }
        });
        pnIngresar.add(lbIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 68, 30));

        pnLogo.add(pnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 70, 30));
        pnLogo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 190, 10));
        pnLogo.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 190, 10));

        getContentPane().add(pnLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 380));

        pnDatos.setBackground(new java.awt.Color(22, 22, 22));
        pnDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/cirpriano.png"))); // NOI18N
        pnDatos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 169, 136));

        pnExit.setBackground(new java.awt.Color(22, 22, 22));

        lbExit.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbExit.setForeground(new java.awt.Color(255, 255, 255));
        lbExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbExit.setText("X");
        lbExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnExitLayout = new javax.swing.GroupLayout(pnExit);
        pnExit.setLayout(pnExitLayout);
        pnExitLayout.setHorizontalGroup(
            pnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnExitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbExit, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnExitLayout.setVerticalGroup(
            pnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnExitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbExit, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnDatos.add(pnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 20, 20));

        getContentPane().add(pnDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 240, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void conUser(){ 
        if(txtUsuario.getText().equals("Ingrese su nombre de usuario")){
            txtUsuario.setText("");
        }
        if(passContra.getText().equals("")){
            passContra.setForeground(new Color(153,153,153));
            passContra.setText("*************");
        } 
    }
    private void conPass(){
        if(passContra.getText().equals("*************")){
            passContra.setText("");
        }
        if(txtUsuario.getText().equals("")){
            txtUsuario.setForeground(new Color(153,153,153));
            txtUsuario.setText("Ingrese su nombre de usuario");
        }
    }
    
    private void enterLogin(java.awt.event.KeyEvent e){
        if(e.getKeyChar() == (char)KeyEvent.VK_ENTER){
                if(txtUsuario.getText().equals("jefferson") || passContra.getText().equals("jeff")){
                    frm.setVisible(true);
                    this.setVisible(false);
                }
                else{
                    //llamamos un frame que indique el error de usuario o contraseña
                    message.setVisible(true);
                }
        }
    }
    
    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void lbExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExitMouseEntered
        pnExit.setBackground(Color.red);
    }//GEN-LAST:event_lbExitMouseEntered

    private void lbExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExitMouseExited
        pnExit.setBackground(new Color(22,22,22));
    }//GEN-LAST:event_lbExitMouseExited

    private void lbExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lbExitMouseClicked

    private void lbIngresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbIngresarMouseEntered
        pnIngresar.setBackground(new Color(44,44,44));
    }//GEN-LAST:event_lbIngresarMouseEntered

    private void lbIngresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbIngresarMouseExited
        pnIngresar.setBackground(new Color(22,22,22));
    }//GEN-LAST:event_lbIngresarMouseExited

    private void txtUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMouseClicked
        conUser();
    }//GEN-LAST:event_txtUsuarioMouseClicked

    private void passContraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passContraMouseClicked
        conPass();
    }//GEN-LAST:event_passContraMouseClicked

    //Esto lo hice por las webas
    private void txtUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMousePressed
        
    }//GEN-LAST:event_txtUsuarioMousePressed

    private void passContraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passContraMousePressed
        
    }//GEN-LAST:event_passContraMousePressed

    ////////////////////
    
    private void txtUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyTyped
        if(evt.getKeyChar() != (char)KeyEvent.VK_ENTER){
            conUser();
        }
        txtUsuario.setForeground(Color.black);
    }//GEN-LAST:event_txtUsuarioKeyTyped

    private void passContraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passContraKeyTyped
        if(evt.getKeyChar() != (char)KeyEvent.VK_ENTER){
            conPass();
        }
        passContra.setForeground(Color.black);
    }//GEN-LAST:event_passContraKeyTyped

    private void lbIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbIngresarMouseClicked
        if(txtUsuario.getText().equals("jefferson") && passContra.getText().equals("jeff")){
            frm.setVisible(true);
            this.setVisible(false);
        }
        else{
            message.setVisible(true);
        }
    }//GEN-LAST:event_lbIngresarMouseClicked

    private void lbIngresarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbIngresarKeyPressed
        //no sirve
    }//GEN-LAST:event_lbIngresarKeyPressed

    private void passContraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passContraKeyPressed
        enterLogin(evt);
    }//GEN-LAST:event_passContraKeyPressed

    private void txtUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyPressed
        enterLogin(evt);
    }//GEN-LAST:event_txtUsuarioKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbExit;
    private javax.swing.JLabel lbIngresar;
    private javax.swing.JPasswordField passContra;
    private javax.swing.JPanel pnDatos;
    private javax.swing.JPanel pnExit;
    private javax.swing.JPanel pnIngresar;
    private javax.swing.JPanel pnLogo;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
