/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.MenuPrincipal;

import java.awt.BorderLayout;
import java.awt.Color;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author PC
 */
public class FrmMenuPrincipal extends javax.swing.JFrame {
    int bandera, flag;
    Timer timer;
    TimerTask tarea;
    pnImages inf;
    FrmPropiedades pro;
    FrmSeccion Fseccion;
    
    public FrmMenuPrincipal() {
        initComponents();
        bandera = 1;//Variable para llevar un control del sombreado oscuro que llevan las opciones: biblioteca, informacion, favoritos y salir
        flag = 1;//Variable que lleva el control de las transiciones de las imagenes
        inf = new pnImages();//Establecemos el panel de images
        Call_panel(inf);//Call_panel llama al panel correspondiente
        bucle();//Inicia el timer que permite el cammbio de imagenes
        pro = new FrmPropiedades();//Objeto para luego mostrar el frame propiedades
        Fseccion = new FrmSeccion();//Objeto para el frame seccion de la barra de opciones del menu
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnOptions = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnBiblioteca = new javax.swing.JPanel();
        lbBiblioteca = new javax.swing.JLabel();
        pnInformacion = new javax.swing.JPanel();
        lbInformacion = new javax.swing.JLabel();
        pnFavoritos = new javax.swing.JPanel();
        lbFavoritos = new javax.swing.JLabel();
        pnSalir = new javax.swing.JPanel();
        lbSalir = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pnShow = new javax.swing.JPanel();
        pnExit = new javax.swing.JPanel();
        lbExit = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        lbPropiedades = new javax.swing.JLabel();
        lbSeccion = new javax.swing.JLabel();
        lbTransImagenes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnOptions.setBackground(new java.awt.Color(22, 22, 22));
        pnOptions.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/cirpriano.png"))); // NOI18N
        pnOptions.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 200, 130));

        pnBiblioteca.setBackground(new java.awt.Color(35, 35, 35));

        lbBiblioteca.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lbBiblioteca.setForeground(new java.awt.Color(153, 153, 153));
        lbBiblioteca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBiblioteca.setText("Biblioteca");
        lbBiblioteca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBiblioteca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBibliotecaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbBibliotecaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbBibliotecaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnBibliotecaLayout = new javax.swing.GroupLayout(pnBiblioteca);
        pnBiblioteca.setLayout(pnBibliotecaLayout);
        pnBibliotecaLayout.setHorizontalGroup(
            pnBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbBiblioteca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        pnBibliotecaLayout.setVerticalGroup(
            pnBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBibliotecaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnOptions.add(pnBiblioteca, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 140, 50));

        pnInformacion.setBackground(new java.awt.Color(22, 22, 22));

        lbInformacion.setBackground(new java.awt.Color(153, 153, 153));
        lbInformacion.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lbInformacion.setForeground(new java.awt.Color(153, 153, 153));
        lbInformacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbInformacion.setText("Informacion");
        lbInformacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbInformacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbInformacionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbInformacionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbInformacionMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnInformacionLayout = new javax.swing.GroupLayout(pnInformacion);
        pnInformacion.setLayout(pnInformacionLayout);
        pnInformacionLayout.setHorizontalGroup(
            pnInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbInformacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnInformacionLayout.setVerticalGroup(
            pnInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnInformacionLayout.createSequentialGroup()
                .addComponent(lbInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnOptions.add(pnInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 140, 50));

        pnFavoritos.setBackground(new java.awt.Color(22, 22, 22));

        lbFavoritos.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lbFavoritos.setForeground(new java.awt.Color(153, 153, 153));
        lbFavoritos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFavoritos.setText("Favoritos");
        lbFavoritos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbFavoritos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbFavoritosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbFavoritosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbFavoritosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnFavoritosLayout = new javax.swing.GroupLayout(pnFavoritos);
        pnFavoritos.setLayout(pnFavoritosLayout);
        pnFavoritosLayout.setHorizontalGroup(
            pnFavoritosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnFavoritosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbFavoritos, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnFavoritosLayout.setVerticalGroup(
            pnFavoritosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnFavoritosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbFavoritos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnOptions.add(pnFavoritos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 140, 50));

        pnSalir.setBackground(new java.awt.Color(22, 22, 22));

        lbSalir.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lbSalir.setForeground(new java.awt.Color(153, 153, 153));
        lbSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSalir.setText("Salir");
        lbSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbSalirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnSalirLayout = new javax.swing.GroupLayout(pnSalir);
        pnSalir.setLayout(pnSalirLayout);
        pnSalirLayout.setHorizontalGroup(
            pnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnSalirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnSalirLayout.setVerticalGroup(
            pnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnSalirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnOptions.add(pnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 140, 50));

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        pnOptions.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 10, 480));

        jPanel1.add(pnOptions, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 530));

        pnShow.setBackground(new java.awt.Color(22, 22, 22));
        pnShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnShowMouseEntered(evt);
            }
        });
        pnShow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnExit.setBackground(new java.awt.Color(22, 22, 22));
        pnExit.setForeground(new java.awt.Color(255, 255, 255));

        lbExit.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbExit.setForeground(new java.awt.Color(255, 255, 255));
        lbExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbExit.setText("X");
        lbExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnExitLayout = new javax.swing.GroupLayout(pnExit);
        pnExit.setLayout(pnExitLayout);
        pnExitLayout.setHorizontalGroup(
            pnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnExitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbExit, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnExitLayout.setVerticalGroup(
            pnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnExitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbExit, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnShow.add(pnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 20, 20));

        content.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 632, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        pnShow.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 632, 410));

        lbPropiedades.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        lbPropiedades.setForeground(new java.awt.Color(153, 153, 153));
        lbPropiedades.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPropiedades.setText("Propiedades");
        lbPropiedades.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbPropiedades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPropiedadesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbPropiedadesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbPropiedadesMouseExited(evt);
            }
        });
        pnShow.add(lbPropiedades, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 80, -1));

        lbSeccion.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        lbSeccion.setForeground(new java.awt.Color(153, 153, 153));
        lbSeccion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbSeccion.setText("Seccion");
        lbSeccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbSeccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbSeccionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbSeccionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbSeccionMouseExited(evt);
            }
        });
        pnShow.add(lbSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 50, -1));

        lbTransImagenes.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        lbTransImagenes.setForeground(new java.awt.Color(153, 153, 153));
        lbTransImagenes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTransImagenes.setText("Transicion de Imagenes");
        lbTransImagenes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbTransImagenes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbTransImagenesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbTransImagenesMouseExited(evt);
            }
        });
        pnShow.add(lbTransImagenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, -1));

        jPanel1.add(pnShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 690, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
   
    public void bucle(){//Funcion para cambiar de imagen cada x segundos
        tarea = new TimerTask(){
            @Override
            public void run(){
                switch(flag){
                    case 1 -> { 
                        flag = 2;                                     
                        inf.lbImage.setIcon(new ImageIcon("C://Users//PC//Documents//NetBeansProjects//App_ElCipriani//src//com//images//sanji.png"));
                    }
                    case 2 -> {
                        flag = 3;
                        inf.lbImage.setIcon(new ImageIcon("C://Users//PC//Documents//NetBeansProjects//App_ElCipriani//src//com//images//yonko.png"));
                    }
                    case 3 -> {
                        flag = 4;
                        inf.lbImage.setIcon(new ImageIcon("C://Users//PC//Documents//NetBeansProjects//App_ElCipriani//src//com//images//teach.jpg"));
                    }
                    case 4 -> {
                        flag = 5;
                        inf.lbImage.setIcon(new ImageIcon("C://Users//PC//Documents//NetBeansProjects//App_ElCipriani//src//com//images//zoro.png"));
                    }
                    case 5 -> {
                        flag = 6;
                        inf.lbImage.setIcon(new ImageIcon("C://Users//PC//Documents//NetBeansProjects//App_ElCipriani//src//com//images//momo.png"));
                    }
                    case 6 -> {
                        flag = 7;
                        inf.lbImage.setIcon(new ImageIcon("C://Users//PC//Documents//NetBeansProjects//App_ElCipriani//src//com//images//redRoc.png"));
                    }
                    case 7 -> {
                        flag = 1;
                        inf.lbImage.setIcon(new ImageIcon("C://Users//PC//Documents//NetBeansProjects//App_ElCipriani//src//com//images//gear five.png"));
                    }
                }
            }
        };
        timer = new Timer();
        timer.scheduleAtFixedRate(tarea, 3000, 3000);//Parametros(tarea a realizar, milisegundos para iniciar, milisegundos para cambiar de imagen a otra)
    }
    
    private void Call_panel(JPanel panel){ //Funcion para llamar a diferentes panales en el menu principal segun se elija una opcion
        panel.setSize(632, 410);
        panel.setLocation(0, 0);
        content.removeAll();
        content.add(panel, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }
    
    private void lbBibliotecaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBibliotecaMouseEntered
        if(bandera != 1){//Condicional para que el sombreado no se borre si es que la opcion esta previamente seleccionada
            pnBiblioteca.setBackground(new Color(50,50,50));
        }    
    }//GEN-LAST:event_lbBibliotecaMouseEntered

    private void lbBibliotecaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBibliotecaMouseExited
        if(bandera != 1){//Condicional para que el sombreado no se borre si es que la opcion esta previamente seleccionada
            pnBiblioteca.setBackground(new Color(22,22,22));
        }
    }//GEN-LAST:event_lbBibliotecaMouseExited

    private void lbInformacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbInformacionMouseEntered
        if(bandera != 2){//Condicional para que el sombreado no se borre si es que la opcion esta previamente seleccionada
        pnInformacion.setBackground(new Color(50,50,50));
        }
    }//GEN-LAST:event_lbInformacionMouseEntered

    private void lbFavoritosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbFavoritosMouseEntered
        if(bandera != 3){//Condicional para que el sombreado no se borre si es que la opcion esta previamente seleccionada
            pnFavoritos.setBackground(new Color(50,50,50));
        }
    }//GEN-LAST:event_lbFavoritosMouseEntered

    private void lbSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSalirMouseEntered
        pnSalir.setBackground(new Color(50,50,50));
    }//GEN-LAST:event_lbSalirMouseEntered

    private void lbInformacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbInformacionMouseExited
        if(bandera != 2){//Condicional para que el sombreado no se borre si es que la opcion esta previamente seleccionada
        pnInformacion.setBackground(new Color(22,22,22));
        }
    }//GEN-LAST:event_lbInformacionMouseExited

    private void lbFavoritosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbFavoritosMouseExited
        if(bandera != 3){//Condicional para que el sombreado no se borre si es que la opcion esta previamente seleccionada
            pnFavoritos.setBackground(new Color(22,22,22));
        }
    }//GEN-LAST:event_lbFavoritosMouseExited

    private void lbSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSalirMouseExited
        pnSalir.setBackground(new Color(22,22,22));
    }//GEN-LAST:event_lbSalirMouseExited

    private void lbSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lbSalirMouseClicked

    private void lbExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExitMouseEntered
        pnExit.setBackground(Color.red);
    }//GEN-LAST:event_lbExitMouseEntered

    private void lbExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lbExitMouseClicked

    private void lbExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExitMouseExited
        pnExit.setBackground(new Color(22,22,22));
    }//GEN-LAST:event_lbExitMouseExited

    private void lbInformacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbInformacionMouseClicked
        pnInformacion.setBackground(new Color(35,35,35));
        bandera = 2;
        //reiniciamos el color de los paneles
        pnBiblioteca.setBackground(new Color(22,22,22));
        pnFavoritos.setBackground(new Color(22,22,22));
        
        //Ponemos el panel de informacion
        pnInformacion inf = new pnInformacion();
        Call_panel(inf);
    }//GEN-LAST:event_lbInformacionMouseClicked

    private void lbBibliotecaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBibliotecaMouseClicked
        pnBiblioteca.setBackground(new Color(35,35,35));
        bandera = 1;
        //reiniciamos el color de los paneles
        pnInformacion.setBackground(new Color(22,22,22));
        pnFavoritos.setBackground(new Color(22,22,22));
        
        //Ponemos el panel de images(biblioteca)
        Call_panel(inf);
    }//GEN-LAST:event_lbBibliotecaMouseClicked

    private void lbFavoritosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbFavoritosMouseClicked
        pnFavoritos.setBackground(new Color(35,35,35));
        bandera = 3;
        //reiniciamos el color de los paneles
        pnInformacion.setBackground(new Color(22,22,22));
        pnBiblioteca.setBackground(new Color(22,22,22));
        
        //Ponemos el panel de favoritos
        pnFavoritos fav = new pnFavoritos();
        Call_panel(fav);
    }//GEN-LAST:event_lbFavoritosMouseClicked

    private void lbPropiedadesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPropiedadesMouseEntered
        lbPropiedades.setForeground(Color.white);
        pro.lbAncho.setText("Ancho: " + content.getWidth() + "px");
        pro.lbLargo.setText("Altura:  " +content.getHeight() + "px");
        pro.lbFecha.setText("Fecha:  13/07/22");
        pro.setLocation(this.getX() + pnShow.getX() + lbPropiedades.getX() + lbPropiedades.getWidth(), this.getY() + lbPropiedades.getY());
        pro.setVisible(true);
    }//GEN-LAST:event_lbPropiedadesMouseEntered

    private void lbSeccionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSeccionMouseEntered
        lbSeccion.setForeground(Color.white);
        Fseccion.setLocation(this.getX() + pnShow.getX() + lbSeccion.getX() + lbSeccion.getWidth(), this.getY() + lbSeccion.getY());
        Fseccion.setVisible(true);     
    }//GEN-LAST:event_lbSeccionMouseEntered

    private void lbTransImagenesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbTransImagenesMouseEntered
        lbTransImagenes.setForeground(Color.white);
    }//GEN-LAST:event_lbTransImagenesMouseEntered

    private void lbPropiedadesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPropiedadesMouseExited
        lbPropiedades.setForeground(new Color(153,153,153));
        pro.setVisible(false);
    }//GEN-LAST:event_lbPropiedadesMouseExited

    private void lbSeccionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSeccionMouseExited
        lbSeccion.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_lbSeccionMouseExited

    private void lbTransImagenesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbTransImagenesMouseExited
        lbTransImagenes.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_lbTransImagenesMouseExited

    private void lbPropiedadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPropiedadesMouseClicked
        pro.setVisible(true);
    }//GEN-LAST:event_lbPropiedadesMouseClicked

    private void pnShowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnShowMouseEntered
        Fseccion.setVisible(false);
        switch(Fseccion.flagSeccion){
            case 1:
                Fseccion.pnAnime.setBackground(new Color(70,70,70));
                Fseccion.lbAnime.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(22,22,22), null));
                break;
            case 2:
                Fseccion.pnFamilia.setBackground(new Color(70,70,70));
                Fseccion.lbFamilia.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(22,22,22), null));
                break;
            case 3:
                Fseccion.pnPeladas.setBackground(new Color(70,70,70));
                Fseccion.lbPeladas.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(22,22,22), null));
                break;
            case 4:
                Fseccion.pnAmigos.setBackground(new Color(70,70,70));
                Fseccion.lbAmigos.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(22,22,22), null));
                break;
        }
    }//GEN-LAST:event_pnShowMouseEntered

    private void lbSeccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSeccionMouseClicked
        Fseccion.setVisible(true);
    }//GEN-LAST:event_lbSeccionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbBiblioteca;
    private javax.swing.JLabel lbExit;
    private javax.swing.JLabel lbFavoritos;
    private javax.swing.JLabel lbInformacion;
    public javax.swing.JLabel lbPropiedades;
    private javax.swing.JLabel lbSalir;
    private javax.swing.JLabel lbSeccion;
    private javax.swing.JLabel lbTransImagenes;
    private javax.swing.JPanel pnBiblioteca;
    private javax.swing.JPanel pnExit;
    private javax.swing.JPanel pnFavoritos;
    private javax.swing.JPanel pnInformacion;
    private javax.swing.JPanel pnOptions;
    private javax.swing.JPanel pnSalir;
    public javax.swing.JPanel pnShow;
    // End of variables declaration//GEN-END:variables
}